version: '3.8'

services:
  local_postgres:
    image: postgres:14.7
    restart: always
    container_name: local_postgres
    hostname: docker_compose_local_psql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      TZ: ${TZ}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data_psql:/var/lib/postgresql/data

  local_psql_admin:
    image: dpage/pgadmin4:6.21
    restart: always
    container_name: local_psql_admin
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data_admin:/var/lib/pgadmin
    depends_on:
      - local_postgres

volumes:
  data_psql:
  data_admin:

